
name: Deploy to VPS

on:
  push:
    branches:
      - dev  # or your default branch name

env:
  DOCKER_IMAGE:  gaddamvinuss/ucsupdatedapp  # Replace with your Docker image name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ env.DOCKER_IMAGE }}:v2
            docker stop ucsupdatedappdeploy || true
            docker rm ucsupdatedappdeploy || true
            docker run -d \
              --name ucsupdatedappdeploy \
              -p 2020:3020 \
              ${{ env.DOCKER_IMAGE }}:v2

